"""Python source provider for EAG."""

from eag.source.python.provider import PythonSourceProvider
from eag.source.python.transformations import (
    CompositeEdit,
    ConflictDetector,
    DiffEngine,
    Edit,
    EditEngine,
    EditTransaction,
    EditType,
    GenerateSymbolTransformation,
    ImportEdit,
    MoveSymbolTransformation,
    OrganizeImportsTransformation,
    RenameTransformation,
    RenameVisitor,
    SafeDeleteTransformation,
    SafeReplaceTransformation,
    SourceEdit,
    StructuredDiff,
    SymbolEdit,
    TextEdit,
    Transformation,
    TransformationBatch,
    TransformationCatalog,
    TransformationCategory,
    TransformationContext,
    TransformationDescriptor,
    TransformationEngine,
    TransformationPreview,
    TransformationRegistry,
    TransformationResult,
    TransformationValidator,
    apply_text_edits,
)
from eag.source.python.transformations.errors import TransactionError

__all__ = [
    "PythonSourceProvider",
    "Transformation",
    "TransformationContext",
    "TransformationEngine",
    "TransformationPreview",
    "TransformationRegistry",
    "TransformationResult",
    "TransformationValidator",
    "TransformationDescriptor",
    "TransformationCategory",
    "TransformationCatalog",
    "RenameTransformation",
    "RenameVisitor",
    "MoveSymbolTransformation",
    "SafeDeleteTransformation",
    "OrganizeImportsTransformation",
    "GenerateSymbolTransformation",
    "SafeReplaceTransformation",
    "Edit",
    "EditType",
    "TextEdit",
    "SymbolEdit",
    "ImportEdit",
    "CompositeEdit",
    "SourceEdit",
    "ConflictDetector",
    "EditEngine",
    "TransformationBatch",
    "EditTransaction",
    "TransactionError",
    "apply_text_edits",
    "DiffEngine",
    "StructuredDiff",
]
