"""Engineering Planning Platform — domain vocabulary, models, errors, and events."""

from eag.planner.approval import (
    ApprovalDecision,
    ApprovalEngine,
    ApprovalFinding,
    ApprovalLevel,
    ApprovalPolicy,
    ApprovalReason,
    ApprovalRequest,
    ApprovalResult,
    ApprovalState,
    AutomaticApprovalPolicy,
    DangerousOperationPolicy,
    OwnershipPolicy,
    RiskApprovalPolicy,
)
from eag.planner.enums import (
    ExecutionMode,
    GoalType,
    PlannerRuntimeState,
    PlanState,
    RiskLevel,
    TaskPriority,
)
from eag.planner.enums import (
    PlanningStrategy as PlanningStrategyType,  # enum (renamed to avoid clash)
)
from eag.planner.errors import (
    ApprovalRequiredError,
    DependencyCycleError,
    DuplicatePlanningStrategyError,
    DuplicateTaskError,
    InvalidGoalError,
    PlanGenerationError,
    PlannerError,
    PlanningExecutionError,
    PlanningStrategyError,
    PlanningStrategyNotFoundError,
    PlanningStrategyUnavailableError,
    PlanningValidationError,
    UnknownDependencyError,
    UnsafePlanError,
)
from eag.planner.events import (
    PlanGenerated,
    PlanningCompleted,
    PlanningFailed,
    PlanningStarted,
    StrategySelected,
)
from eag.planner.intelligence import (
    EffortEstimator,
    EngineeringComplexity,
    EngineeringExecutionProfile,
    EngineeringGoal,
    EngineeringIntelligencePipeline,
    EngineeringOperation,
    EngineeringPlanningArtifact,
    EngineeringRiskAssessment,
    EngineeringRiskFactor,
    EngineeringScope,
    GoalAnalyzer,
    RiskAnalyzer,
    TaskDecomposer,
    TaskDependencyGraph,
    TaskDependencyNode,
    TaskDependencyResolver,
    TaskDependencyStatistics,
)
from eag.planner.models import (
    EngineeringTask,
    ExecutionAction,
    ExecutionPlan,
    ExecutionStep,
    PlanningContext,
    PlanningGoal,
    PlanningResult,
    PlanningRuntimeHealth,
    PlanningRuntimeMetrics,
    PlanningStatistics,
    PlanningStrategyInfo,
)
from eag.planner.operations import (
    EngineeringOperationDefinition,
    OperationCategory,
    OperationComplexity,
    OperationExecutionContext,
    OperationExecutionResult,
    OperationRegistry,
    OperationSafety,
    default_operation_registry,
)
from eag.planner.registry import PlanningStrategyRegistry
from eag.planner.runtime import PlannerRuntime
from eag.planner.simulation import (
    EngineeringSimulationReport,
    PlanSimulator,
    SimulationCheckpoint,
    SimulationImpact,
    SimulationStatus,
    SimulationTimeline,
)
from eag.planner.strategies import SequentialStrategy
from eag.planner.strategy import PlanningStrategy
from eag.planner.validation import (
    EngineeringPlanValidationResult,
    PlanValidationRule,
    PlanValidator,
    ValidationCategory,
    ValidationIssue,
    ValidationSeverity,
)

__all__ = [
    # Enums
    "ExecutionMode",
    "GoalType",
    "PlanState",
    "PlannerRuntimeState",
    "PlanningStrategyType",
    "RiskLevel",
    "TaskPriority",
    # Errors
    "ApprovalRequiredError",
    "DependencyCycleError",
    "DuplicatePlanningStrategyError",
    "DuplicateTaskError",
    "InvalidGoalError",
    "PlanGenerationError",
    "PlannerError",
    "PlanningExecutionError",
    "PlanningStrategyError",
    "PlanningStrategyNotFoundError",
    "PlanningStrategyUnavailableError",
    "PlanningValidationError",
    "UnknownDependencyError",
    "UnsafePlanError",
    # Events
    "PlanGenerated",
    "PlanningCompleted",
    "PlanningFailed",
    "PlanningStarted",
    "StrategySelected",
    # Intelligence
    "EffortEstimator",
    "EngineeringComplexity",
    "EngineeringExecutionProfile",
    "EngineeringGoal",
    "EngineeringIntelligencePipeline",
    "EngineeringOperation",
    "EngineeringPlanningArtifact",
    "EngineeringRiskAssessment",
    "EngineeringRiskFactor",
    "EngineeringScope",
    "GoalAnalyzer",
    "RiskAnalyzer",
    "TaskDecomposer",
    "TaskDependencyGraph",
    "TaskDependencyNode",
    "TaskDependencyResolver",
    "TaskDependencyStatistics",
    # Models
    "EngineeringTask",
    "ExecutionAction",
    "ExecutionPlan",
    "ExecutionStep",
    "PlanningContext",
    "PlanningGoal",
    "PlanningResult",
    "PlanningRuntimeHealth",
    "PlanningRuntimeMetrics",
    "PlanningStatistics",
    "PlanningStrategyInfo",
    # Operations
    "EngineeringOperationDefinition",
    "OperationCategory",
    "OperationComplexity",
    "OperationExecutionContext",
    "OperationExecutionResult",
    "OperationRegistry",
    "OperationSafety",
    "default_operation_registry",
    # Registry & Strategy
    "PlanningStrategyRegistry",
    "PlanningStrategy",
    "SequentialStrategy",
    # Runtime
    "PlannerRuntime",
    # Simulation
    "EngineeringSimulationReport",
    "PlanSimulator",
    "SimulationCheckpoint",
    "SimulationImpact",
    "SimulationStatus",
    "SimulationTimeline",
    # Validation
    "EngineeringPlanValidationResult",
    "PlanValidationRule",
    "PlanValidator",
    "ValidationCategory",
    "ValidationIssue",
    "ValidationSeverity",
    # Approval
    "ApprovalDecision",
    "ApprovalEngine",
    "ApprovalFinding",
    "ApprovalLevel",
    "ApprovalPolicy",
    "ApprovalReason",
    "ApprovalRequest",
    "ApprovalResult",
    "ApprovalState",
    "AutomaticApprovalPolicy",
    "DangerousOperationPolicy",
    "OwnershipPolicy",
    "RiskApprovalPolicy",
]
